[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fmroi"
authors = [{name = "proactionlab", email = "proactiondev@uc.pt"}]
dynamic = ["version", "description"]
